### ISSUE TITLE
NotSupportedException thrown by SA1602EnumerationItemsMustBeDocumented

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#1359]
I suspect that this is because of trying to use an `ImmutableDictionary<>` in a type that's used with the JSON serializer. I'm sure it will try to call `IDictionary<T>.Add()` when populating a dictionary property if it isn't null initially.

My brand new settings file uses the *variables* property.

    Severity	Code	Description	Project	File	Line	Detail Description
    Message	AD0001	The User Diagnostic Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1602EnumerationItemsMustBeDocumented' threw an exception of type 'System.NotSupportedException' with message 'Specified method is not supported.'.	JW.Admin.ServiceInterface		1	Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1602EnumerationItemsMustBeDocumented' threw the following exception:
    'System.NotSupportedException: Specified method is not supported.
       at System.Collections.Immutable.ImmutableDictionary`2.System.Collections.IDictionary.set_Item(Object key, Object value)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
       at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
       at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
       at StyleCop.Analyzers.SettingsHelper.GetStyleCopSettings(ImmutableArray`1 additionalFiles)
       at StyleCop.Analyzers.SettingsHelper.GetStyleCopSettings(AnalyzerOptions options)
       at StyleCop.Analyzers.DocumentationRules.SA1602EnumerationItemsMustBeDocumented.Analyzer..ctor(AnalyzerOptions options)
       at StyleCop.Analyzers.DocumentationRules.SA1602EnumerationItemsMustBeDocumented.HandleCompilationStart(CompilationStartAnalysisContext context)
       at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass25_0.<ExecuteCompilationStartActions>b__0()
       at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.

**Comment by sharwell** [comment]
Interesting. [It works here in the tests.](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/NoXmlFileHeaderUnitTests.cs#L24-L27) Wonder what's different.

**Comment by oatkins** [comment]
I just found that out too! Could something else be loading a different version of the Newtonsoft serializer into the AppDomain?

**Comment by pdelvo** [comment]
visual studio could have loaded json.net

**Comment by oatkins** [comment]
Even if I downgrade json.net all the way back to a version from 2013 I still can't get the test to fail. Maybe it could be related to the version of System.Collections.Immutable used at runtime.

Anyway, the workaround is easy: don't use variables.

**Comment by sharwell** [comment]
I found the underlying problem. Grabbing this to implement a workaround.
