### ISSUE TITLE
SA1600 (Elements must be documented) throws InvalidCastException

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#1416]
I get the following exception, though I can't see what code is causing this. It has me scratching my head, since I can't work out how the parent of a method declaration could be a compilation unit.

```
Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1600ElementsMustBeDocumented' threw the following exception:
'System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.BaseTypeDeclarationSyntax'.
   at StyleCop.Analyzers.Helpers.AccessLevelHelper.GetEffectiveAccessibility(BaseMethodDeclarationSyntax syntax, SemanticModel semanticModel, CancellationToken cancellationToken)
   at StyleCop.Analyzers.DocumentationRules.SA1600ElementsMustBeDocumented.Analyzer.HandleMethodDeclaration(SyntaxNodeAnalysisContext context)
   at StyleCop.Analyzers.AnalyzerExtensions.<>c__DisplayClass2_0`1.<RegisterSyntaxNodeActionHonorExclusions>b__0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass35_0`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.
```

**Comment by sharwell** [comment]
Do you have a method defined outside of a type?

**Comment by oatkins** [comment]
I have 17,000 source files, so I'm not sure!

I didn't think that was ever valid C# syntax. Delegates can be outside of a type, but I wouldn't have thought that they would come through as `BaseMethodDeclarationSyntax`.

Could the exception have been thrown on incomplete code while I was typing in the editor? I can't reproduce that though.

**Comment by oatkins** [comment]
OK. I managed to reproduce this. A public method placed in the global scope is invalid, but still get analyzed, and so you still see the exception.

**Comment by hvanbakel** [comment]
Grabbed
