### ISSUE TITLE
NullReferenceException in SA1313 (ParameterNamesMustBeginWithLowerCaseLetter)

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1529]
I received the following exception in SA1313 on **CodeContracts.sln**.

```
'System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.NamingRules.SA1313ParameterNamesMustBeginWithLowerCaseLetter.NameMatchesAbstraction(ParameterSyntax syntax, SemanticModel semanticModel) in J:\dev\github\sharwell\StyleCopAnalyzers\StyleCop.Analyzers\StyleCop.Analyzers\NamingRules\SA1313ParameterNamesMustBeginWithLowerCaseLetter.cs:line 152
   at StyleCop.Analyzers.NamingRules.SA1313ParameterNamesMustBeginWithLowerCaseLetter.HandleParameterSyntax(SyntaxNodeAnalysisContext context) in J:\dev\github\sharwell\StyleCopAnalyzers\StyleCop.Analyzers\StyleCop.Analyzers\NamingRules\SA1313ParameterNamesMustBeginWithLowerCaseLetter.cs:line 88
   at StyleCop.Analyzers.AnalyzerExtensions.<>c__DisplayClass2_0`1.<RegisterSyntaxNodeActionHonorExclusions>b__0(SyntaxNodeAnalysisContext c) in J:\dev\github\sharwell\StyleCopAnalyzers\StyleCop.Analyzers\StyleCop.Analyzers\AnalyzerExtensions.cs:line 87
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass35_0`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.
```

**Comment by Noryoko** [comment]
Grabbing this.
