### ISSUE TITLE
SA1120 threw an ArgumentOutOfRangeException exception: 'Length cannot be less than zero'

### ISSUE THREAD

**Issue by NikolayIT** [DotNetAnalyzers/StyleCopAnalyzers#2056]
The `SA1120CommentsMustContainText` just threw an exception in my Visual Studio 2015:

	Warning	AD0001	Analyzer 'StyleCop.Analyzers.ReadabilityRules.SA1120CommentsMustContainText' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Length cannot be less than zero.
	Parameter name: length'.	PressCenters.Sources		1	Active	Analyzer 'StyleCop.Analyzers.ReadabilityRules.SA1120CommentsMustContainText' threw the following exception:
	'System.ArgumentOutOfRangeException: Length cannot be less than zero.
	Parameter name: length
	   at System.String.Substring(Int32 startIndex, Int32 length)
	   at StyleCop.Analyzers.ReadabilityRules.SA1120CommentsMustContainText.HandleMultiLineComment(SyntaxTreeAnalysisContext context, SyntaxTrivia multiLineComment)
	   at StyleCop.Analyzers.ReadabilityRules.SA1120CommentsMustContainText.HandleSyntaxTree(SyntaxTreeAnalysisContext context)
	   at StyleCop.Analyzers.AnalyzerExtensions.<>c__DisplayClass2_0.<RegisterSyntaxTreeActionHonorExclusions>b__0(SyntaxTreeAnalysisContext c)
	   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass37_0.<ExecuteSyntaxTreeActionsCore>b__0()
	   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.

**Comment by sharwell** [comment]
I can reproduce this by placing `/*` at the end of a file (*not* followed by a newline).

It's a fairly minor issue since it only appears in code which will not otherwise compile. Marking up-for-grabs and targeting 1.1.0 Beta 1.

**Comment by NikolayIT** [comment]
:+1: The same action causes the exception at my side.
