### ISSUE TITLE
NullRef in ReadabilityRules SA1129 

### ISSUE THREAD

**Issue by jmckone3** [DotNetAnalyzers/StyleCopAnalyzers#2150]
Versions:
VS2015, .Net 4.5.1.1, Analyzers 1.0

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.ReadabilityRules.SA1129DoNotUseDefaultValueTypeConstructor.HandleObjectCreationExpression(SyntaxNodeAnalysisContext context)
   at StyleCop.Analyzers.AnalyzerExtensions.<>c__DisplayClass4_0`1.<RegisterSyntaxNodeActionHonorExclusions>b__0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
```

**Comment by sharwell** [comment]
Thanks for the report!

**Comment by pdelvo** [comment]
Thats weird. I don't see anything in this method that could possibly throw a NullReferenceException. The only explaination I have is that some of the method calls got inlined and a NullReferenceException was thrown somewhere else. The IsReferenceTypeParameter can not throw a NRE so the only other option is one of the calls into roslyn source.

**Comment by sharwell** [comment]
This appears to be a duplicate of #1668, which we thought was fixed a while back.

@jmckone3 Can you confirm the *exact* version of the package you are working with?

**Comment by jmckone3** [comment]
Still had Beta15.  Have since updated.  Will report if any repro.  Thanks and sorry for randomizing.

**Comment by sharwell** [comment]
@jmckone3 No problem, glad it was such an easy fix! :smile:
