### ISSUE TITLE
SA1008 threw a NullReferenceException

### ISSUE THREAD

**Issue by appel1** [DotNetAnalyzers/StyleCopAnalyzers#2354]
Using StyleCopAnalyzers 1.0 in VS2017 for a .NET 4.5 project, C#6. While refactoring I got the following error. At some point during my refactorings the file referenced in the error was removed, don't know if that is related or if this error occurred before that.  

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'StyleCop.Analyzers.SpacingRules.SA1008OpeningParenthesisMustBeSpacedCorrectly' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	<project>	1	Active	Analyzer 'StyleCop.Analyzers.SpacingRules.SA1008OpeningParenthesisMustBeSpacedCorrectly' threw the following exception:
'Exception occurred with following context:
Compilation: <project>
SyntaxTree: <source path>

System.NullReferenceException: Object reference not set to an instance of an object.
   at StyleCop.Analyzers.Helpers.LocationHelpers.GetLineSpan(SyntaxToken token)
   at StyleCop.Analyzers.SpacingRules.SA1008OpeningParenthesisMustBeSpacedCorrectly.HandleOpenParenToken(SyntaxTreeAnalysisContext context, SyntaxToken token)
   at StyleCop.Analyzers.SpacingRules.SA1008OpeningParenthesisMustBeSpacedCorrectly.HandleSyntaxTree(SyntaxTreeAnalysisContext context)
   at StyleCop.Analyzers.AnalyzerExtensions.<>c__DisplayClass2_0.<RegisterSyntaxTreeActionHonorExclusions>b__0(SyntaxTreeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass41_0.<ExecuteSyntaxTreeActionsCore>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

**Comment by vweijsters** [comment]
I had a quick look at the sources and I don't see an obvious bug there. The call stack indicates that either the token being processed (the opening parenthesis) or the previous token has a `SyntaxTree` property that returns null. I can't quite figure out yet under what circumstances that can happen.
