### ISSUE TITLE
SA1649 code fix crashes when renaming file

### ISSUE THREAD

**Issue by onyxmaster** [DotNetAnalyzers/StyleCopAnalyzers#2520]
Visual Studio 15.3.1, attempting to rename a file "<snip>\Services\HistoricalData\Implementation\RateHistoryClassMap.cs" to "<snip>\Services\HistoricalData\Implementation\FullRateHistoryEntryClassMap.cs".

The stack trace is as follows:
```
System.AggregateException : One or more errors occurred. ---> Could not find file '<snip>\Services\HistoricalData\Implementation\RateHistoryClassMap.cs'.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.IO.FileNotFoundException : Could not find file 'C<snip>\Services\HistoricalData\Implementation\RateHistoryClassMap.cs'.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode,IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.InvisibleEditor..ctor(IServiceProvider serviceProvider,String filePath,IVisualStudioHostProject projectOpt,Boolean needsSave,Boolean needsUndoDisabled)
   at Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace.OpenInvisibleEditor(IVisualStudioHostDocument hostDocument)
   at Microsoft.VisualStudio.LanguageServices.RoslynVisualStudioWorkspace.OpenInvisibleEditor(DocumentId documentId)
   at Microsoft.VisualStudio.LanguageServices.Implementation.GlobalUndoServiceFactory.WorkspaceUndoTransaction.AddDocument(DocumentId id)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---
```

**Comment by MoamenMohamed** [comment]
any news about this bug ??

**Comment by vweijsters** [comment]
@sharwell What should we do with this one? There is no reference to any StyleCop.Analyzers code in the call stack. I'm tempted to say that this one is external.

**Comment by sharwell** [comment]
Is there a Roslyn issue for a better file rename API?

**Comment by vweijsters** [comment]
Probably this one: dotnet/roslyn#6261

**Comment by bjornhellander** [comment]
For the record: There is now a Renamer.RenameDocument method available from version 3.7 of Microsoft.CodeAnalysis.Workspaces.Common, which seems to require Visual Studio 16.7.

**Comment by sharwell** [comment]
We should be able to invoke that via a light-up layer for cases where it is supported.
