### ISSUE TITLE
SA1100 threw an exception of type 'System.InvalidOperationException' with message 'This program location is thought to be unreachable.'

### ISSUE THREAD

**Issue by bbarry** [DotNetAnalyzers/StyleCopAnalyzers#3103]
I'm getting this build error when nullable reference types are enabled with the included test case:

```
1>CSC : warning AD0001: Analyzer 'StyleCop.Analyzers.ReadabilityRules.SA1100DoNotPrefixCallsWithBaseUnlessLocalImplementationExists' threw an exception of type 'System.InvalidOperationException' with message 'This program location is thought to be unreachable.'.
```

```csharp
namespace ClassLibrary1
{
    using System.IdentityModel.Tokens.Jwt;
    using System.Security.Claims;
    using Microsoft.IdentityModel.Tokens;

    public class AlgorithmValidator : JwtSecurityTokenHandler
    {
        public override ClaimsPrincipal ValidateToken(
            string token,
            TokenValidationParameters validationParameters,
            out SecurityToken validatedToken)
        {
            var principle = base.ValidateToken(token, validationParameters, out var temp);
            validatedToken = temp;
            return principle;
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.113" IncludeAssets="Analyzers;Build" PrivateAssets="All" />
  </ItemGroup>
</Project>
```

I am able to get rid of the warning either by removing the local variable `temp`  or by turning off nullable reference types.

**Comment by bbarry** [comment]
possibly triggering https://github.com/dotnet/roslyn/issues/39993?

**Comment by sharwell** [comment]
Are you also seeing this inside Visual Studio? If so, can you include the exception stack trace?

**Comment by bbarry** [comment]
The build error doesn't have an attached exception but the intellisense error does:

```
Analyzer 'StyleCop.Analyzers.ReadabilityRules.SA1100DoNotPrefixCallsWithBaseUnlessLocalImplementationExists' threw the following exception:
'Exception occurred with following context:
Compilation: ClassLibrary1
SyntaxTree: C:\Users\bbarry\source\repos\ClassLibrary1\ClassLibrary1\AlgorithmValidator.cs
SyntaxNode: base [BaseExpressionSyntax]@[452..456) (13,28)-(13,32)

System.InvalidOperationException: This program location is thought to be unreachable.
   at Microsoft.CodeAnalysis.CSharp.Binder.BindOutVariableDeclarationArgument(DeclarationExpressionSyntax declarationExpression, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindOutDeclarationArgument(DeclarationExpressionSyntax declarationExpression, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentValue(DiagnosticBag diagnostics, ArgumentSyntax argumentSyntax, Boolean allowArglist, RefKind refKind)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentAndName(AnalyzedArguments result, DiagnosticBag diagnostics, Boolean& hadError, Boolean& hadLangVersionError, ArgumentSyntax argumentSyntax, Boolean allowArglist, Boolean isDelegateCreation)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSpeculativelyBoundExpression(Int32 position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption, Binder& binder, ImmutableArray`1& crefSymbols)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSpeculativelyBoundExpression(Int32 position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption, Binder& binder, ImmutableArray`1& crefSymbols)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfo(Int32 position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption)
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSpeculativeSymbolInfo(SemanticModel semanticModel, Int32 position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption)
   at StyleCop.Analyzers.ReadabilityRules.SA1100DoNotPrefixCallsWithBaseUnlessLocalImplementationExists.HandleBaseExpression(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__55`1.<ExecuteSyntaxNodeAction>b__55_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
```

I am not sure that there is anything to fix here in this project except wait for VS 2019 16.5 where I think this may be fixed (I don't have the ability to install the preview to test it).

**Comment by sharwell** [comment]
Yep, this is a Roslyn bug.
