### ISSUE TITLE
SA1201 throws KeyNotFoundException for certain (invalid syntax) code

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#3160]
```
Severity	Code	Description	Project	File	Line	Tool
Warning	AD0001	Analyzer 'StyleCop.Analyzers.OrderingRules.SA1201ElementsMustAppearInTheCorrectOrder' threw an exception of type 'System.Collections.Generic.KeyNotFoundException' with message 'The given key was not present in the dictionary.'.
Exception occurred with following context:
Compilation: VSServiceBrokerSample
SyntaxTree: D:\Users\andarno\source\repos\VSServiceBrokerSample\VSServiceBrokerSample\FilePicker\IWorkspace.cs
SyntaxNode: using System.Threading; using System ... [CompilationUnitSyntax]@[64..1246) (2,0)-(41,0)

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at StyleCop.Analyzers.OrderingRules.SA1201ElementsMustAppearInTheCorrectOrder.HandleMemberList(SyntaxNodeAnalysisContext context, ImmutableArray`1 elementOrder, Int32 kindIndex, SyntaxList`1 members, ImmutableArray`1 order)
   at StyleCop.Analyzers.OrderingRules.SA1201ElementsMustAppearInTheCorrectOrder.HandleCompilationUnit(SyntaxNodeAnalysisContext context, StyleCopSettings settings)
   at StyleCop.Analyzers.AnalyzerExtensions.<>c__DisplayClass3_0`1.<RegisterSyntaxNodeAction>b__0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__58`1.<ExecuteSyntaxNodeAction>b__58_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: SA1201	VSServiceBrokerSample		1	StyleCop.Analyzers
```

**Repro**

Add the following code to any .cs source file. It doesn't matter that there will be many compile errors. Just look for the AD0001 error.

```cs
    public class Foo
    {
                private void Execute(object sender, EventArgs e)
        {
            this.package.JoinableTaskFactory.RunAsync(async delegate
            {
                try
                {
                    using (var c = await this.serviceBrokerClient.GetProxyAsync<x>(y))
                    {
if (c.Proxy is object) {)
                    }

                
                }
                catch (Exception ex)
                {
                    await this.package.JoinableTaskFactory.SwitchToMainThreadAsync();
                    MessageDialog.Show("Error", ex.Message, MessageDialogCommandSet.RetryCancel);
                }
            });
        }

    }
```

**Comment by vweijsters** [comment]
I can't reproduce this in VS2019 16.6.5. Based on the provided call stack I've made a pull request to workaround this issue.
