### ISSUE TITLE
Exception running FixAll for SA1518 on msbuild

### ISSUE THREAD

**Issue by elachlan** [DotNetAnalyzers/StyleCopAnalyzers#3425]
I received this exception running the solution wide fix all for msbuild:
```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: charsToReplace
   at Microsoft.VisualStudio.Text.Implementation.BaseBuffer.Edit.Replace(Int32 startPosition,Int32 charsToReplace,String replaceWith)
   at Microsoft.VisualStudio.Text.Implementation.BaseBuffer.Edit.Replace(Span replaceSpan,String replaceWith)
   at Microsoft.CodeAnalysis.Text.Extensions.SnapshotSourceText.WithChanges(IEnumerable`1 changes)
   at async StyleCop.Analyzers.LayoutRules.SA1518CodeFixProvider.FixEndOfFileAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StyleCop.Analyzers.LayoutRules.SA1518CodeFixProvider.FixAll.FixAllInDocumentAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StyleCop.Analyzers.Helpers.DocumentBasedFixAllProvider.GetSolutionFixesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
```

**Comment by bjornhellander** [comment]
Which StyleCopAnalyzers and Visual Studio versions were you using, @elachlan?
Can you reproduce this, or did it just happen once?

**Comment by elachlan** [comment]
> Which StyleCopAnalyzers and Visual Studio versions were you using, @elachlan?
> Can you reproduce this, or did it just happen once?

It's in the description. I ran it against the msbuild solution. There is a linked issue. It reproduced every time I tried it.

**Comment by bjornhellander** [comment]
No versions and no linked issue, as far as I can see.

Anyway, I checked out msbuild, reset to commit caf7d291ca40377bd4712d787b07f8a1f86ebb34 (which is around when you started your code cleanup) and added StyleCop beta 406. That got me a single SA1518 in SubToolset.cs, but no exceptions when fixing it. Can you provide a link to something that reproduces this?

**Comment by elachlan** [comment]
@bjornhellander I have tried again on the main branch and it is working. So something has been fixed between Jan and now.
