### ISSUE TITLE
SA1649 Throws an exception with Record types. 

### ISSUE THREAD

**Issue by ryadavilli** [DotNetAnalyzers/StyleCopAnalyzers#3643]
Exception details are as below:

```
Error	AD0001
	Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1649FileNameMustMatchTypeName' threw an exception of type 'System.ArgumentException' with message 'Unhandled declaration kind: RecordDeclaration'.
Exception occurred with following context:
Compilation: <project name>
SyntaxTree: <path to file>
With the below exception
System.ArgumentException: Unhandled declaration kind: RecordDeclaration
   at StyleCop.Analyzers.Helpers.NamedTypeHelpers.GetNameOrIdentifier(MemberDeclarationSyntax member)
   at StyleCop.Analyzers.Helpers.FileNameHelpers.GetConventionalFileName(MemberDeclarationSyntax declaration, FileNamingConvention convention)
   at StyleCop.Analyzers.DocumentationRules.SA1649FileNameMustMatchTypeName.Analyzer.HandleSyntaxTree(SyntaxTreeAnalysisContext context, StyleCopSettings settings)
   at StyleCop.Analyzers.AnalyzerExtensions.<>c__DisplayClass0_0.<RegisterSyntaxTreeAction>b__0(SyntaxTreeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSyntaxTreeActionsCore>b__59_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

```

**Comment by bjornhellander** [comment]
This looks like a duplicate of #3215, which was fixed in 1.2.0-beta.261. Which version are you using? Version 1.1.118 is for example too old for "modern" language features like this, so a beta version will unfortunately be needed.
